### Übungsblatt 1 ###
- Tim
- Karla
- Marcel
- Lennox
$$ \frac{1}{2}$$

In [2]:
print("Hello World") #prints hello world

Hello World


In [2]:
import numpy as np
# d)
d = np.array([1,2,3])
print("d:")
print(d)
# e)
e = np.array([[1],[2],[3],[4]])
print("e:")
print(e)

# f)
print("f:")
f = np.zeros((3,3))
print(f)
# g)
print("g:")
g = np.random.randint(0, 2, (4, 3))
print(g[2])
# h)
print("h:")
h = np.random.randint(0, 2, (4, 4))
print(h[:,-1])
#i)
print("i:")
i = np.transpose(h)
print(i)



d:
[1 2 3]
e:
[[1]
 [2]
 [3]
 [4]]
f:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
g:
[0 0 0]
h:
[1 1 1 1]
i:
[[0 1 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 1 1 1]]


In [37]:
#j)
print("j:")
j_0 = np.random.randint(0, 2, (3, 3))
j_1 = np.random.randint(0,2,(3,3))
new_matrix = np.empty((3,3))
for i in range(3):
    for j in range(3):
        temp_sum = 0
        for k in range(3):
            temp_sum += j_0[i, k] * j_1[k, j]
        new_matrix[i, j] = temp_sum
print(new_matrix)

print("now with numpy dot:")
print(np.dot(j_0, j_1)) 
#k)
print("k:")
h_stack = np.hstack((j_0, j_1))
v_stack = np.vstack((j_0, j_1))
print("h_stack:")
print (h_stack)
print("v_stack:")
print (v_stack)

#l)
print("l:")
print(j_0.shape)



j:
[[0. 2. 1.]
 [1. 1. 2.]
 [1. 0. 1.]]
now in less ugly and more efficient:
[[0 2 1]
 [1 1 2]
 [1 0 1]]
k:
h_stack:
[[0 1 1 1 0 1]
 [1 0 1 0 1 0]
 [1 0 0 0 1 1]]
v_stack:
[[0 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]
 [0 1 1]]
l:
(3, 3)


In [41]:
#m)
print("m:")
m = np.random.randint(0, 2, (8, 7))
print("original 8x7 shape:" )
print(m)
print("reshaped to 14x4:")
print(m.reshape(14,4))

m:
original 8x7 shape:
[[1 1 1 1 0 0 0]
 [0 1 1 1 1 1 1]
 [0 0 0 1 1 0 1]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0]]
reshaped to 14x4:
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 0 0]
 [0 1 1 0]
 [1 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 1 0 0]]


In [45]:
#n)
print("n:")
n = np.random.randint(0, 2, (3, 1))
print("n:")
print(n)
print("n tiled 10000 times:")
print(np.tile(n, (1, 10000)))

#o)
print("o:")


n:
n:
[[1]
 [1]
 [1]]
n tiled 10000 times:
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [3]:
#o)
matrix = np.array([[ 1, -2,  3],
                   [-4,  5, -6],
                   [ 7, -8,  9]])

negative_mask = matrix < 0

matrix[negative_mask] = 0
print("o:")
print("Modified Matrix:")
print(matrix)

Modified Matrix:
[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [14]:
#p)
print("p:")
p = np.arange(1,101,7)
print(p)
#q)
print("q:")
q = np.arange(1,101)
q[1::2] = 0
print(q)
#r)
print("r:")
r = np.delete(np.arange(1,101), np.s_[1::2])
print(r)

p:
[ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99]
q:
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23  0
 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47  0
 49  0 51  0 53  0 55  0 57  0 59  0 61  0 63  0 65  0 67  0 69  0 71  0
 73  0 75  0 77  0 79  0 81  0 83  0 85  0 87  0 89  0 91  0 93  0 95  0
 97  0 99  0]
r:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [19]:
#s)
print("s:")
print(np.identity(3))
#t)
print("t:")
t = np.random.randint(0,2,(5,5))
print(t)
print("diagonal:")
print(np.diag(t))



s:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
t:
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 1]
 [1 0 0 1 0]
 [0 0 0 0 1]]
diagonal:
[0 0 1 1 1]


### Aufgabe 3 ###

In [27]:

#a)
# Erzeuge die ersten und zweiten Matrizen mit Zufallszahlen
matrix1 = np.random.rand(1000, 3)
matrix2 = np.random.rand(1000, 3)

# Erstelle eine leere Matrix für die Skalarprodukte
scalar_products = np.zeros((1000, 1000))


In [29]:
%%timeit
for i, row1 in enumerate(matrix1):
    for j, row2 in enumerate(matrix2):
        scalar_products[i, j] = np.dot(row1, row2)


523 ms ± 3.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
%%timeit
scalar_products = np.einsum('ij,kj->ik', matrix1, matrix2)

3.72 ms ± 87.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Unterschiede ###
Es war so ca Faktor 100 schneller numpy zu nehmen. Und das obwohl ich noch np.dot genutzt hatte es ist also deutlich effizienter numpy zu nutzen.


In [ ]:
#s
matrizen = np.random.rand(1000, 4)
determinant = matrizen[:,0] * matrizen[:,3] - matrizen[:,1] * matrizen[:,2]
invertierbar = np.where(determinant != 0)

