### Übungsblatt 1 ###
- Tim
- Karla
- Marcel
- Lennox
$$ \frac{1}{2}$$

In [2]:
print("Hello World") #prints hello world

Hello World


In [32]:
import numpy as np
# d)
d = np.array([1,2,3])
print("d:")
print(d)
# e)
e = np.array([[1],[2],[3],[4]])
print("e:")
print(e)

# f)
print("f:")
f = np.zeros((3,3))
print(f)
# g)
print("g:")
g = np.random.randint(0, 2, (4, 3))
print(g[2])
# h)
print("h:")
h = np.random.randint(0, 2, (4, 4))
print(h[:,-1])
#i)
print("i:")
i = np.transpose(h)
print(i)



d:
[1 2 3]
e:
[[1]
 [2]
 [3]
 [4]]
f:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
g:
[1 0 0]
h:
[0 1 0 0]
i:
[[1 1 1 0]
 [1 0 0 0]
 [1 0 0 1]
 [0 1 0 0]]


In [37]:
#j)
print("j:")
j_0 = np.random.randint(0, 2, (3, 3))
j_1 = np.random.randint(0,2,(3,3))
new_matrix = np.empty((3,3))
for i in range(3):
    for j in range(3):
        temp_sum = 0
        for k in range(3):
            temp_sum += j_0[i, k] * j_1[k, j]
        new_matrix[i, j] = temp_sum
print(new_matrix)

print("now with numpy dot:")
print(np.dot(j_0, j_1)) 
#k)
print("k:")
h_stack = np.hstack((j_0, j_1))
v_stack = np.vstack((j_0, j_1))
print("h_stack:")
print (h_stack)
print("v_stack:")
print (v_stack)

#l)
print("l:")
print(j_0.shape)



j:
[[0. 2. 1.]
 [1. 1. 2.]
 [1. 0. 1.]]
now in less ugly and more efficient:
[[0 2 1]
 [1 1 2]
 [1 0 1]]
k:
h_stack:
[[0 1 1 1 0 1]
 [1 0 1 0 1 0]
 [1 0 0 0 1 1]]
v_stack:
[[0 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]
 [0 1 1]]
l:
(3, 3)


In [41]:
#m)
print("m:")
m = np.random.randint(0, 2, (8, 7))
print("original 8x7 shape:" )
print(m)
print("reshaped to 14x4:")
print(m.reshape(14,4))

m:
original 8x7 shape:
[[1 1 1 1 0 0 0]
 [0 1 1 1 1 1 1]
 [0 0 0 1 1 0 1]
 [0 0 1 1 0 0 0]
 [0 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0]]
reshaped to 14x4:
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 0 0]
 [0 1 1 0]
 [1 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 1 0 0]]


In [45]:
#n)
print("n:")
n = np.random.randint(0, 2, (3, 1))
print("n:")
print(n)
print("n tiled 10000 times:")
print(np.tile(n, (1, 10000)))

#o)
print("o:")


n:
n:
[[1]
 [1]
 [1]]
n tiled 10000 times:
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
